<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WarningLevel>8</WarningLevel>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Title>Koturn.Zopfli</Title>
    <Version>2.2.1</Version>
    <Authors>koturn</Authors>
    <Company>koturn</Company>
    <Description>A P/Invoke library for google/zopfli (zopfli.dll and zopflipng.dll).</Description>
    <Copyright>Copyright (C) 2020 koturn All Rights Reserverd.</Copyright>
    <PackageProjectUrl>https://github.com/koturn/Koturn.Zipfli</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/koturn/Koturn.Zipfli</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>zopfli;zopflipng</PackageTags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.6.3" Condition="'$(TargetFramework)'=='netstandard2.0'" />
  </ItemGroup>

</Project>
