version: 2.1.1.{build}
image: Visual Studio 2022
init:
- cmd: '"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"'
install:
- cmd: >-
    git submodule update --init

    nmake /nologo restore
build_script:
- cmd: >-
    nmake /nologo

    nmake /nologo deploy
test_script:
- cmd: nmake /nologo test
artifacts:
- path: Koturn.Zopfli-netstandard2.0.zip
  name: .NET standard 2.0 binary
- path: Koturn.Zopfli-net8.0.zip
  name: .NET 8.0 binary
- path: Koturn.Zopfli-net9.0.zip
  name: .NET 9.0 binary
