version: 1.0.{build}
image: Visual Studio 2022
install:
- cmd: >-
    "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"

    nmake restore
build_script:
- cmd: >-
    nmake

    nmake deploy
artifacts:
- path: ZopfliSharp-netstandard2.0.zip
  name: ZopfliSharp-netstandard2.0
- path: ZopfliSharp-net8.0.zip
  name: ZopfliSharp-net8.0.zip
- path: ZopfliSharp-net9.0.zip
  name: ZopfliSharp-net9.0
