version: 2.1.0.{build}
image: Visual Studio 2022
init:
- cmd: '"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"'
install:
- cmd: >-
    git submodule update --init

    nmake restore
build_script:
- cmd: >-
    nmake

    nmake deploy
artifacts:
- path: Koturn.Zopfli-netstandard2.0.zip
  name: Koturn.Zopfli-netstandard2.0
- path: Koturn.Zopfli-net8.0.zip
  name: Koturn.Zopfli-net8.0.zip
- path: Koturn.Zopfli-net9.0.zip
  name: Koturn.Zopfli-net9.0
